### ISSUE TITLE
Would this be able to detect ransomware behavior

### ISSUE THREAD

**Issue by 2fast4u4everlol** [ilovemilk/ransomware_detection#10]
I paid for this skin pack from skinpacks.com and now Bitdefender Total Security is saying it has detected ransomware behaviour from this file
![Screenshot (2)](https://user-images.githubusercontent.com/49545268/56714869-70a3d680-6779-11e9-9b49-b59298a579bc.png)

**Comment by 2fast4u4everlol** [comment]
the one that is highlighted

**Comment by ilovemilk** [comment]
Hi,
no this file wouldn't bei detected by the ransomware app.  Bitdefender detects such files by performing signature scans. It's possible to setup clamav for Nextcloud which does the same (see more: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/antivirus_configuration.html).

The ransomware app would be able to detect ransomware behaviour if the ransomware would be executed and the modified files would be uploaded to a Nextcloud instance with the app installed.
