### ISSUE TITLE
Error	PHP	Error: Class 'OCA\RansomwareDetection\Analyzer\SequenceResult' not found at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/SequenceAnalyzer.php

### ISSUE THREAD

**Issue by Githopp192** [ilovemilk/ransomware_detection#7]
### Steps to reproduce
Enable APP:  Ransomware Recovery
Disable APP: Ransomware Recovery

Solved by: Disable/Enable APP: Ransomware Protection

### Expected behaviour
no PHP Errors; normal CPU HTTP Load

### Actual behaviour
CPU jumped to 100% Load, there were a lot of HTTP Sessions (Apache), Web-Server becomes almost unresponsive

Error	PHP	Error: Class 'OCA\RansomwareDetection\Analyzer\SequenceResult' not found at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/SequenceAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileExtensionAnalyzer.php#94	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileTypeFunnellingAnalyzer.php#65	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileTypeFunnellingAnalyzer.php#65	11 hours ago
Error	PHP	Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileTypeFunnellingAnalyzer.php#65

## Server configuration detail

**Operating system:** Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64

**Webserver:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.24 (apache2handler)

**Database:** mysql 5.5.60

**PHP version:** 

7.1.24
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache

**Nextcloud version:** 13.0.8 - 13.0.8.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - announcementcenter: 3.2.1
 - apporder: 0.6.0
 - bookmarks: 0.12.2
 - bruteforcesettings: 1.2.0
 - calendar: 1.6.1
 - circles: 0.14.3
 - comments: 1.3.0
 - contacts: 2.1.5
 - data_request: 1.0.1
 - dav: 1.4.7
 - deck: 0.5.1
 - drop_account: 0.0.12
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_antivirus: 1.4.2
 - files_external: 1.4.1
 - files_fulltextsearch: 1.0.4
 - files_pdfviewer: 1.2.1
 - files_rightclick: 0.8.4
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.8
 - fulltextsearch: 1.0.3
 - gallery: 18.0.0
 - impersonate: 1.0.4
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mindmaps: 0.1.0
 - mood: 0.4.0
 - music: 0.9.3
 - nextcloud_announcements: 1.2.0
 - notes: 2.5.1
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - ownbackup: 18.11.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - polls: 0.8.3
 - provisioning_api: 1.3.0
 - quicknotes: 0.1.4
 - quota_warning: 1.2.0
 - radio: 0.6.1
 - rainloop: 5.1.0
 - ransomware_protection: 1.1.2
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - sharepoint: 1.1.0
 - sharerenamer: 1.7.0
 - socialsharing_diaspora: 1.0.3
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - socialsharing_googleplus: 1.0.3
 - socialsharing_twitter: 1.0.3
 - spreed: 3.2.6
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.8
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - appvncsafe
 - audioplayer
 - carnet
 - cms_pico
 - encryption
 - external
 - files_markdown
 - lsd
 - phonetrack
 - richdocuments
 - spreedme
 - user_external
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxx",
        "xxxx"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxxxx",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "13.0.8.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "updater.release.channel": "production",
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "data-fingerprint": "xxxxxx",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "session_lifetime": 1200,
    "session_keepalive": false,
    "logtimezone": "xxxxx",
    "logfile": "\/media\/log\/nextcloud.log",
    "knowledgebaseenabled": false,
    "log_rotate_size": 3145728
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by ilovemilk** [comment]
Hi Githopp,

thanks for report this problem. Do I understand you correctly, you are just disabling the ransomware recovery application and then this problem pops up?
Because enabling/disabling the app, which is together installed with the ransomware protection application, doesn't trigger the problem for me. I tested it with Nextcloud version 13.0.4 / 14 / 15.

**Comment by Githopp192** [comment]
Hi Matthis
sorry for this later answer .. was very busy .. yes, i think i did disable the application .. and it did Pop up .. meanwhile i did the upgrade to NC14.0.4 and i did not yet enable this app again .. because this is a production Environment .. i got NC unresponsive the last time due those Errors and a lot of HTTP Requests and HTTP-Services which led the CPU grow to 100%. Maybe you could find anything in the meanwhile ?!

Best regards
Mike

**Comment by ilovemilk** [comment]
Hi Githopp192,
Thanks for your answer. I tried to reproduce it on my raspberry pi, root server and also my docker containers with different users and files but I wasn't able to trigger the problem.

Do you have many big files stored on your Nextcloud instance?

Maybe the pull request by lars_sh will fix the issue for you because it removes these errors.

Best regards
Matthias

**Comment by Githopp192** [comment]
Hi Matthias

Hm, maybe the Cloud has got some big files  (some small movies from some users) .. bot so many .. i think about 100-300 Files ..

Yes, let’s hope the «lars_sh» pull can fix the issue ☺

Have a great Sunday and thx4 your support.

Best Regards
Mike

Von: Matthias <notifications@github.com>
Gesendet: Sonntag, 13. Januar 2019 17:15
An: ilovemilk/ransomware_detection <ransomware_detection@noreply.github.com>
Cc: Githopp192 <bigpanther@hotmail.ch>; Author <author@noreply.github.com>
Betreff: Re: [ilovemilk/ransomware_detection] Error PHP Error: Class 'OCA\RansomwareDetection\Analyzer\SequenceResult' not found at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/SequenceAnalyzer.php (#7)


Hi Githopp192,
Thanks for your answer. I tried to reproduce it on my raspberry pi, root server and also my docker containers with different users and files but I wasn't able to trigger the problem.

Do you have many big files stored on your Nextcloud instance?

Maybe the pull request by lars_sh will fix the issue for you because it removes these errors.

Best regards
Matthias

**Comment by ilovemilk** [comment]
How big approx are these files? Maybe I can simulate your files.

Thanks you too 😄 

Best regards
Matthias

**Comment by cwhitsbm** [comment]
We are also having this same issue.  Although we only enabled Ransomware today, I just happened to notice this error in our logs.  But we are getting this error in our log about every 5 seconds or so.  We are running NC15.02.  Galera Cluster 10.3, PHP 7.3


Error | PHP | Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88 |   | 2019-02-21T19:09:12-0800
-- | -- | -- | -- | --
Error | PHP | Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88 |   | 2019-02-21T19:09:12-0800
Error | PHP | Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88 |   | 2019-02-21T19:09:12-0800
Error | PHP | Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88 |   | 2019-02-21T19:09:12-0800
Error | PHP | Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88 |   | 2019-02-21T19:09:12-0800
Error | PHP | Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88 |   | 2019-02-21T19:09:12-0800
Error | PHP | Undefined index: extension at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/FileCorruptionAnalyzer.php#88 |   | 2019-02-21T19:09:12-0800

**Comment by ilovemilk** [comment]
Hi cwhitsbm,

Thanks for the info I forgot to release a new version and publish it to the Nextcloud Appstore.
I will do it this weekend and notify you when it's done! Hopefully, you can test again it with the new version. :)

Best regards,
Matthias

**Comment by ilovemilk** [comment]
Hi,

I released a new version! I would be happy if you could try it out.

Best regards,
Matthias

**Comment by cwhitsbm** [comment]
FYI...  this did resolve our issue.
