### ISSUE TITLE
Storage wrapper 'ransomware_protection' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

### ISSUE THREAD

**Issue by SimJoSt** [ilovemilk/ransomware_detection#9]
I have a lot of the following messages in my Nextcloud log:
```
Storage wrapper 'ransomware_protection' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.
```

Nextcloud: 15.0.4.0
Installierte Apps: 94
PHP: 7.2.15
Datenbank: mysql

**Comment by ilovemilk** [comment]
Hi SimJoSt,

I think you are in the wrong repository: The namespace of my application is "ransomware_detection", the "ransomware_protection" guys can be found there: https://github.com/nextcloud/ransomware_protection

Best regards,
Matthias
